Do not throw error in Big Number Calculator when the base of the exponent is 1
uccser/cs-field-guide pull request #1340
Opened 2020-10-27 06:58 UTC by courtneycb

This issue was raised to us by a user.

If the base is 1 then the calculator still throws an error.
![BNC](https://user-images.githubusercontent.com/16066822/97266770-e9fc1800-188d-11eb-8381-252b5f5a9aac.png)

This can happen because:
1. The `pow` function in Big.js can not handle calculations where the exponent is greater than 1 million.
2. We check if the combined digit length of x and y is greater or equal to 10, if it is we throw an error.

We now check if the base (x) is equal to 1, if it is we just set the result to 1. I removed the check for the combined digit length of x and y being greater or equal to 10 because we display the error message if the number cannot be calculated anyway. This means that if the number can be calculated it will be, else it will display the error message. I didn't see a reason to have this restriction? Let me know if it's there for a reason.

Also included a word change requested by Tim.

2020-11-17 01:57 UTC, eAlasdair commented
> I removed the check for the combined digit length of x and y being greater or equal to 10 because:
> 1   If the exponent was 1 and the base had 10 or more digits an error would be thrown.
> 2   We display the error message if the number can't be calculated anyway. This means that if the number can be calculated it will be, else it will display the error message. I also didn't see a reason to have this restriction? Let me know if it's there for a reason.

The automatic restriction doesn't appear to work all that well, ie 9^999999 is allowed (both live and in this pr) yet I had to stop my browser after 5 minutes of it trying. Similarly 9999^999999 is rejected on the old BNC (due to 10 chars) but is allowed (and doesn't finish) in your PR with the manual restriction removed.

2020-11-18 06:28 UTC, courtneycb commented
> > I removed the check for the combined digit length of x and y being greater or equal to 10 because:
> > 1   If the exponent was 1 and the base had 10 or more digits an error would be thrown.
> > 2   We display the error message if the number can't be calculated anyway. This means that if the number can be calculated it will be, else it will display the error message. I also didn't see a reason to have this restriction? Let me know if it's there for a reason.
> 
> The automatic restriction doesn't appear to work all that well, ie 9^999999 is allowed (both live and in this pr) yet I had to stop my browser after 5 minutes of it trying. Similarly 9999^999999 is rejected on the old BNC (due to 10 chars) but is allowed (and doesn't finish) in your PR with the manual restriction removed.

Added an edit to my PR description to describe the changes I made!

2021-01-11 22:27 UTC, eAlasdair requested changes
It's a bit jarring to be hitting the different calculation buttons and suddenly the thing freezes for a few seconds. Could you change the result box to `Calculating...` or something while it calculates instead of leaving the old result there?

2021-01-11 22:30 UTC, eAlasdair commented
Also don't let it queue more button presses! Disable the buttons or something

2021-01-12 22:43 UTC, eAlasdair commented on csfieldguide/static/interactives/big-number-calculator/css/big-number-calculator.scss
> +.calculating {
```suggestion
#interactive-big-number-calculator div#interactive-big-number-calculator-result.calculating {
```

For consistency

2021-02-04 21:45 UTC, eAlasdair approved these changes

2021-08-12 01:00 UTC, JackMorganNZ approved these changes

2021-08-12 01:08 UTC, merged