Fix link to "Entropy (information theory)" Wikipedia entry
uccser/cs-field-guide pull request #2566
Opened 2024-03-23 09:02 UTC by mckzm

Make "Entropy and information theory" inline link compatible with older markdown implementations.

fixes #2565

Newer Markdown implementations (e.g. GitHub's as of this writing) properly render an inline link[0] whose link destination[1] includes parenthesis. Older ones fail, and, as a result, what should be rendered as:

href="https://en.wikipedia.org/wiki/Entropy_(information_theory)"

is instead rendered as:

href="https://en.wikipedia.org/wiki/Entropy_(information_theory"

(closing parenthesis elided/wrong URL)

Wrapping the link destination within angle brackets solves that issue in a way that should be forward-compatible.

[0] https://spec.commonmark.org/0.31.2/#inline-link
[1] https://spec.commonmark.org/0.31.2/#link-destination

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request:

### Checklist

*Change the space in the box to an `x` for those you have completed.
You can also fill these out after creating the pull request.
If you're unsure about any of them, don't hesitate to ask.
We're here to help!
This is simply a reminder of what we are going to look for before merging your change.*

- [ ] I have read the contribution guidelines.
- [ ] I have linked any relevant existing issues/suggestions in the description above (include `#???` in your description to reference an issue, where `???` is the issue number).
- [ ] The pull request is requesting a merge into the `develop` branch.
- [ ] I have added necessary documentation (if appropriate).
- [ ] If I've added/modified/deleted a third-party system, I've updated the relevant license files.
- [ ] I have added myself to the 'Community Contributors' section of `csfieldguide/templates/appendices/contributors.html`

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc.
Feel free to add any images that might be helpful to understand the initial problem/solution.

2024-03-26 20:07 UTC, jimbonothing64 commented
Thanks @mckzm  for spotting and documenting this.

Unfortunately, when visiting https://cs-field-guide.localhost/en/chapters/coding-introduction/further-reading/, I get a `TemplateSyntaxError` :
```
Could not parse the remainder: '<https://en.wikipedia.org/wiki/Entropy_(information_theory' from '<https://en.wikipedia.org/wiki/Entropy_(information_theory'
```
Here is line 14 (offending line) of the template:
```
14: 	<li><a href="{% url <https://en.wikipedia.org/wiki/Entropy_(information_theory %}" target="_blank">Entropy and information theory</a>&gt;)</li>
```

This could be a bug in [verto](https://github.com/uccser/verto), our markdown renderer, where it doesn't support this feature of markdown correctly. It's worth investigating.

2024-03-27 20:27 UTC, jimbonothing64 commented
I've added a test to [verto](https://github.com/uccser/verto). It is a bug where links in <> are not rendered correctly. Your change *should* work, so once verto is fixed to support this markdown feature, I will approve your pull.

@mckzm, in the meantime, could you please add yourself to the to the 'Community Contributors' section of csfieldguide/templates/appendices/contributors.html in this commit?

2024-03-28 05:37 UTC, mckzm commented
Thanks @jimbonothing64.

I have just added myself to the tail of the 'Community Contributors'  list and update the PR.

I've found 5 more instances of the same "dangling paren" problem in various links - would you prefer me to file one issue & PR/instance, or group them all into a single one?

2024-04-18 21:54 UTC, jimbonothing64 commented
Apologies for the delayed response. Your issue and pull request have raised some very interesting points and uncovered other interesting issues!

At some point, verto should be updated to better support links; fixing verto requires more work/time than I'm can dedicate to this problem.

@mckzm, we should move to your simpler solution, from https://github.com/uccser/cs-field-guide/issues/2565: replacing `(` and `)` with `%28` and `%29`, respectively. 

Could you please update your pull to replacing both the initial link and also the extra 5 links you discovered?

Thanks heaps!

2024-04-19 03:12 UTC, mckzm commented
@jimbonothing64 all done :-)

2024-04-19 03:25 UTC, jimbonothing64 requested changes
Thanks so much! One link has a typo, once that's fixed I'll merge your changes in. Thanks again!

2024-04-19 03:25 UTC, jimbonothing64 commented on csfieldguide/chapters/content/en/software-engineering/sections/further-reading.md
> +- [Wikipedia &ndash; Abstraction](https://en.wikipedia.org/wiki/Abstraction_&28computer_science%29)
should be `%28` here, not `%29`

2024-04-19 03:55 UTC, mckzm commented on csfieldguide/chapters/content/en/software-engineering/sections/further-reading.md
> +- [Wikipedia &ndash; Abstraction](https://en.wikipedia.org/wiki/Abstraction_&28computer_science%29)
Ooops sorry about that - now fixed!

2024-04-19 03:58 UTC, jimbonothing64 approved these changes
Thanks!

2024-04-19 03:59 UTC, jimbonothing64 approved these changes

2024-04-19 04:00 UTC, merged